version: "3.9"
   
services:
  prophunt_small_1:
    image: ethorbit/srcds-server:latest   # Combined autoupdating srcds installation
    network_mode: host
    volumes:
      - prophunt_small_1:/home/srcds/server # retain volume per service to improve startup time. If changing game signifiantly, remove volume between reboots to allow recreate
    environment:
      - SRCDS_APPID=${SERVER1_APPID:-4020}  # Steam App ID. Check if game has a dedicated server version, eg 4000 is GMOD, 4020 is the GMOD Dedicated Server
      - SRCDS_RUN_ARGS='+gamemode "${SERVER1_GAMEMODE:-prophunt}" +rcon_password "${SERVER1_RCON_PASSWORD}" +host_workshop_collection ${SERVER1_COLLECTION:-657069545} +password "${SERVER1_PASSWORD:-password}" +hostname "${SERVER1_NAME:-PNH Server}" +port ${SERVER1_PORT:-27015} +ticrate 66 +map ${SERVER1_MAP:-gm_flatgrass}' # Any runtime args for the server

volumes:
  prophunt_small_1: